# Site settings
name: Gianni Giusto
title: Gianni Giusto | Data Engineer
description: Data solutions enabler
url: https://giustogianni.github.io/
baseurl: ''
email: gianni.giusto@outlook.com
cover: https://giustogianni.github.io/img/og.png
logo: https://giustogianni.github.io/img/emojis/rocket.png
resume: https://www.linkedin.com/in/giannigiusto #https://giustogianni.github.io/resume.pdf
social:
  - title: email
    url: mailto:gianni.giusto@outlook.com
  - title: github
    url: https://github.com/giustogianni
  - title: linkedin
    url: https://www.linkedin.com/in/giannigiusto

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
